// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToDatabase(arg1) {
  return window['go']['main']['App']['ConnectToDatabase'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetTableData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2, arg3);
}

export function GetTables() {
  return window['go']['main']['App']['GetTables']();
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}
