// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectToDatabase(arg1:number):Promise<void>;

export function DeleteConnection(arg1:number):Promise<void>;

export function GetConnections():Promise<Array<main.Connection>>;

export function GetTableData(arg1:string,arg2:number,arg3:number):Promise<main.TableData>;

export function GetTables():Promise<Array<main.TableInfo>>;

export function TestConnection(arg1:string,arg2:string):Promise<void>;
